---

- name: Check Python-3.5.0 installed
  shell: python3 --version | awk '{print $2}'
  ignore_errors: true
  register: python_version

- name: Copy dl_python-3.5.0.sh file
  template:
    src: tmp/dl_python-3.5.0.sh.j2
    dest: /tmp/dl_python-3.5.0.sh
    owner: root
    group: root
    mode: 0655
  when: python_version.stdout != '3.5.0'

- name: Unpack Python-3.5.0.tgz
  unarchive:
    src: common-roles/python/templates/tmp/Python-3.5.0.tgz
    dest: /tmp/
  when: python_version.stdout != '3.5.0'

- name: Install python-3.5.0
  shell: /tmp/dl_python-3.5.0.sh
  when: python_version.stdout != '3.5.0'

- name: Create python symbolic link
  file: src=/usr/local/python/bin/python3 dest=/usr/local/bin/python state=link
  when: python_version.stdout != '3.5.0'

- name: Create pip symbolic link
  file: src=/usr/local/python/bin/pip3.5 dest=/usr/local/bin/pip state=link
  when: python_version.stdout != '3.5.0'

- name: Create python symbolic link
  file:
    src: /usr/local/python/bin/python3
    dest: /usr/bin/python3
    state: link
    owner: root
    group: root
    mode: 0655
  when: python_version.stdout != '3.5.0'