---

- name: Create log directory
  file:
    path: /var/log/nginx/dl.yukihirai0505.com
    state: directory
    owner: nginx
    group: adm
    mode: 0644

- name: Create access log
  file:
    path: /var/log/nginx/dl.yukihirai0505.com/access.log
    state: touch
    owner: nginx
    group: adm
    mode: 0644

- name: Create error log
  file:
    path: /var/log/nginx/dl.yukihirai0505.com/error.log
    state: touch
    owner: nginx
    group: adm
    mode: 0644

- name: Copy the nginx configuration file (/etc/nginx/conf.d/dl.conf)
  template:
    src: etc/nginx/conf.d/dl.conf.j2
    dest: /etc/nginx/conf.d/dl.conf
    owner: root
    group: root
    mode: 0644
  notify: reload nginx

- include: playapp.yml