---

- name: Create log directory
  file:
    path: /var/log/nginx/www.yukihirai0505.com
    state: directory
    owner: nginx
    group: adm
    mode: 0644

- name: Create access log
  file:
    path: /var/log/nginx/www.yukihirai0505.com/access.log
    state: touch
    owner: nginx
    group: adm
    mode: 0644

- name: Create error log
  file:
    path: /var/log/nginx/www.yukihirai0505.com/error.log
    state: touch
    owner: nginx
    group: adm
    mode: 0644

- name: Copy the nginx proxy configuration file (/etc/nginx/conf.d/default_ssl.conf)
  template:
    src: etc/nginx/conf.d/default_ssl.conf.j2
    dest: /etc/nginx/conf.d/default_ssl.conf
    owner: root
    group: root
    mode: 0644
  notify: reload nginx

- name: Install Java8
  yum: {name: 'java-1.8.0-openjdk-devel', state: 'present'}
