---

- name: Install libselinux-python
  yum: name=libselinux-python state=installed

- name: Add nginx repo
  template:
    src: etc/yum.repos.d/nginx.repo.j2
    dest: /etc/yum.repos.d/nginx.repo
    owner: root
    group: root
    mode: 0644

- name: Install nginx
  yum: name=nginx state=present

- name: Setting logrotate nginx (mode 644)
  template:
    src: etc/logrotate.d/nginx.j2
    dest: /etc/logrotate.d/nginx
    owner: root
    group: root
    mode: 0644
  notify: restart rsyslog

- name: Change nginx log-directory permission
  file:
    path: /var/log/nginx
    state: directory
    mode: 0755

- name: Enable nginx service
  service: name=nginx state=started enabled=yes

- name: Change nginx log-file permission
  file:
    path: /var/log/nginx/{{ item }}
    state: file
    mode: 0644
  with_items:
    - access.log
    - error.log

- name: Copy the LTSV log-format file
  template:
    src: etc/nginx/log_format_ltsv.j2
    dest: /etc/nginx/log_format_ltsv
    owner: root
    group: root
    mode: 0644
  when: nginx_use_ltsv_logformat

- name: Copy the nginx configuration file (/etc/nginx/nginx.conf)
  template:
    src: etc/nginx/nginx.conf.j2
    dest: /etc/nginx/nginx.conf
    owner: root
    group: root
    mode: 0644
  notify: reload nginx

- name: Create log directory
  file:
    path: /var/log/nginx/{{ item }}.yukihirai0505.com
    state: directory
    owner: nginx
    group: adm
    mode: 0644
  with_items:
    - www
    - portfolio
    - todo

- name: Create access log
  file:
    path: /var/log/nginx/{{ item }}.yukihirai0505.com/access.log
    state: touch
    owner: nginx
    group: adm
    mode: 0644
  with_items:
    - www
    - portfolio
    - todo

- name: Create error log
  file:
    path: /var/log/nginx/{{ item }}.yukihirai0505.com/error.log
    state: touch
    owner: nginx
    group: adm
    mode: 0644
  with_items:
    - www
    - portfolio
    - todo

- name: Create templates.d directory
  file:
    path: /etc/nginx/templates.d
    state: directory

- name: Copy ssl configuration file (/etc/nginx/templates.d/ssl.conf)
  template:
    src: etc/nginx/templates.d/ssl.conf.j2
    dest: /etc/nginx/templates.d/ssl.conf
    owner: root
    group: root
    mode: 0644

- name: Copy the nginx proxy configuration file (/etc/nginx/conf.d/nginx.conf)
  template:
    src: etc/nginx/conf.d/{{ item }}.j2
    dest: /etc/nginx/conf.d/{{ item }}
    owner: root
    group: root
    mode: 0644
  with_items:
    - proxy.conf
    - upstream.conf
    - default_ssl.conf
    - portfolio.conf
    - todo.conf
  notify: reload nginx

##- debug: var=nginx.remove_default_conf

- include: remove_defaults.yml
  when: nginx_remove_default_conf
