---

- name: Create supervisord ini file [photo-library]
  template:
    src: etc/supervisord.d/photo-library.ini.j2
    dest: /etc/supervisord.d/photo-library.ini
    owner: root
    group: root
    mode: 0644
  notify: restart photo-library

- name: Configure supervisorctl [photo-library]
  supervisorctl:
    name: photo-library
    state: present
  ignore_errors: True

- name: Create supervisord ini file [portfolio]
  template:
    src: etc/supervisord.d/portfolio.ini.j2
    dest: /etc/supervisord.d/portfolio.ini
    owner: root
    group: root
    mode: 0644
  notify: restart portfolio

- name: Configure supervisorctl [portfolio]
  supervisorctl:
    name: portfolio
    state: present
  ignore_errors: True