---

- name: Install git
  yum: name='git' state='present'

- name: Clone letsencrypt repo
  git:
    repo=https://github.com/letsencrypt/letsencrypt
    dest={{ansible_env.PWD}}/letsencrypt version=master accept_hostkey=yes